using System;
using System.Data.Entity;
using System.Data.Entity.Validation;
using System.Linq;

namespace MiLB.Web.Models
{
    public class DataContextInitializer : DropCreateDatabaseIfModelChanges<DataContext>
    {
        protected override void Seed(DataContext context)
        {
            base.Seed(context);

            context.Leagues.AddRange(new[]
            {
                new League { Id = 1, Name = "Appalachian", Slug = "appalachian" },
                new League { Id = 2, Name = "California", Slug = "california" },
                new League { Id = 3, Name = "Carolina", Slug = "carolina" },
                new League { Id = 4, Name = "Eastern", Slug = "eastern" },
                new League { Id = 5, Name = "Florida State", Slug = "florida-state" },
                new League { Id = 6, Name = "International", Slug = "international" },
                new League { Id = 7, Name = "Midwest", Slug = "midwest" },
                new League { Id = 8, Name = "New York-Penn", Slug = "new-york-penn" },
                new League { Id = 9, Name = "Northwest", Slug = "northwest" },
                new League { Id = 10, Name = "Pacific Coast", Slug = "pacific-coast" },
                new League { Id = 11, Name = "Pioneer", Slug = "pioneer" },
                new League { Id = 12, Name = "South Atlantic", Slug = "south-atlantic" },
                new League { Id = 13, Name = "Southern", Slug = "southern" },
                new League { Id = 14, Name = "Texas", Slug = "texas" }
            });

            context.SaveChanges();

            context.Mascots.AddRange(new[]
            {
                new Mascot { Id = 1, TeamId = 1, Name = "Celery", Slug = "celery", IsChampion = false, TwitterHandle = "BisonsCelery" },
                new Mascot { Id = 2, TeamId = 2, Name = "Homer the Dragon", Slug = "homer-the-dragon", IsChampion = false },
                new Mascot { Id = 3, TeamId = 3, Name = "LouSeal", Slug = "louseal", IsChampion = true, TwitterHandle = "ClippersLouSeal" },
                new Mascot { Id = 4, TeamId = 4, Name = "Wool E. Bull", Slug = "wool-e-bull", IsChampion = false, TwitterHandle = "WoolEBull" },
                new Mascot { Id = 5, TeamId = 5, Name = "Chopper", Slug = "chopper", IsChampion = false, TwitterHandle = "ChopperGBraves" },
                new Mascot { Id = 6, TeamId = 6, Name = "Rowdie", Slug = "rowdie", IsChampion = false, TwitterHandle = "RowdieBear" },
                new Mascot { Id = 7, TeamId = 7, Name = "Hambone", Slug = "hambone", IsChampion = false, TwitterHandle = "Go_Hambone" },
                new Mascot { Id = 8, TeamId = 8, Name = "Buddy Bat", Slug = "buddy-bat", IsChampion = false, TwitterHandle = "buddybat" },
                new Mascot { Id = 9, TeamId = 9, Name = "Rip Tide", Slug = "rip-tide", IsChampion = false, TwitterHandle = "therealriptide" },
                new Mascot { Id = 10, TeamId = 10, Name = "Paws", Slug = "paws", IsChampion = false },
                new Mascot { Id = 11, TeamId = 11, Name = "Spikes", Slug = "spikes", IsChampion = false, TwitterHandle = "SpikesAndMittsy" },
                new Mascot { Id = 12, TeamId = 12, Name = "Quills", Slug = "quills", IsChampion = false },
                new Mascot { Id = 13, TeamId = 13, Name = "Scooch", Slug = "scooch", IsChampion = false },
                new Mascot { Id = 14, TeamId = 14, Name = "Muddy the Mud Hen", Slug = "muddy-the-mud-hen", IsChampion = false },
                new Mascot { Id = 15, TeamId = 15, Name = "Orbit", Slug = "orbit", IsChampion = false, TwitterHandle = "Orbit_Isotopes" },
                new Mascot { Id = 16, TeamId = 16, Name = "Sox the Fox", Slug = "sox-the-fox", IsChampion = false },
                new Mascot { Id = 17, TeamId = 17, Name = "Parker", Slug = "parker", IsChampion = true, TwitterHandle = "TheRealParkerB" },
                new Mascot { Id = 18, TeamId = 18, Name = "Cubbie Bear", Slug = "cubbie-bear", IsChampion = false },
                new Mascot { Id = 19, TeamId = 19, Name = "Cosmo", Slug = "cosmo", IsChampion = false },
                new Mascot { Id = 20, TeamId = 20, Name = "Rockey Redbird", Slug = "rockey-redbird", IsChampion = false },
                new Mascot { Id = 21, TeamId = 21, Name = "Ozzie", Slug = "ozzie", IsChampion = false, TwitterHandle = "OzzieTheMascot" },
                new Mascot { Id = 22, TeamId = 22, Name = "Boudreaux D. Nutria", Slug = "boudreaux-d-nutria", IsChampion = false },
                new Mascot { Id = 23, TeamId = 23, Name = "Cooper", Slug = "cooper", IsChampion = false },
                new Mascot { Id = 24, TeamId = 24, Name = "Stormy", Slug = "stormy", IsChampion = false },
                new Mascot { Id = 25, TeamId = 25, Name = "Archie", Slug = "archie", IsChampion = false, TwitterHandle = "archieaceball" },
                new Mascot { Id = 26, TeamId = 26, Name = "Spike", Slug = "spike", IsChampion = false, TwitterHandle = "Spike_RRE" },
                new Mascot { Id = 27, TeamId = 27, Name = "Dinger", Slug = "dinger", IsChampion = false, TwitterHandle = "RCDinger" },
                new Mascot { Id = 28, TeamId = 28, Name = "Bumble", Slug = "bumble", IsChampion = false },
                new Mascot { Id = 29, TeamId = 29, Name = "Rhubarb the Reindeer", Slug = "rhubarb-the-reindeer", IsChampion = false, TwitterHandle = "RainiersRhubarb" },
                new Mascot { Id = 30, TeamId = 30, Name = "Kino Bambino", Slug = "kino-bambino", IsChampion = false, TwitterHandle = "padresmascot" },
                new Mascot { Id = 31, TeamId = 31, Name = "Orbit", Slug = "orbit-2", IsChampion = false, TwitterHandle = "AerosOrbit" },
                new Mascot { Id = 32, TeamId = 32, Name = "Steamer", Slug = "steamer", IsChampion = false },
                new Mascot { Id = 33, TeamId = 33, Name = "Hot Dog Horse", Slug = "hot-dog-horse", IsChampion = false, TwitterHandle = "thehotdoghorse" },
                new Mascot { Id = 34, TeamId = 34, Name = "Louie", Slug = "louie", IsChampion = false },
                new Mascot { Id = 35, TeamId = 35, Name = "C. Wolf", Slug = "c-wolf", IsChampion = true },
                new Mascot { Id = 36, TeamId = 36, Name = "Rascal", Slug = "rascal", IsChampion = false, TwitterHandle = "sensrascal00" },
                new Mascot { Id = 37, TeamId = 37, Name = "Rocky", Slug = "rocky", IsChampion = false, TwitterHandle = "OfficialRocky9" },
                new Mascot { Id = 38, TeamId = 38, Name = "Fungo the Fisher Cat", Slug = "fungo-the-fisher-cat", IsChampion = false },
                new Mascot { Id = 39, TeamId = 39, Name = "Slugger the Sea Dog", Slug = "slugger-the-sea-dog", IsChampion = false, TwitterHandle = "Slugger_SeaDog" },
                new Mascot { Id = 40, TeamId = 40, Name = "Crazy Hot Dog Vendor", Slug = "crazy-hot-dog-vendor", IsChampion = false, TwitterHandle = "CrazyHotDogVndr" },
                new Mascot { Id = 41, TeamId = 41, Name = "Nutzy", Slug = "nutzy", IsChampion = false },
                new Mascot { Id = 42, TeamId = 42, Name = "Boomer", Slug = "boomer", IsChampion = false },
                new Mascot { Id = 43, TeamId = 43, Name = "Babe Ruff", Slug = "babe-ruff", IsChampion = false },
                new Mascot { Id = 44, TeamId = 44, Name = "Looie the Lookout", Slug = "looie-the-lookout", IsChampion = false },
                new Mascot { Id = 45, TeamId = 45, Name = "Homer the Pole Cat", Slug = "homer-the-pole-cat", IsChampion = false, TwitterHandle = "homer_polecat" },
                new Mascot { Id = 46, TeamId = 46, Name = "Chimpy", Slug = "chimpy", IsChampion = false },
                new Mascot { Id = 47, TeamId = 47, Name = "Southpaw", Slug = "southpaw", IsChampion = false },
                new Mascot { Id = 48, TeamId = 48, Name = "Trusty", Slug = "trusty", IsChampion = false },
                new Mascot { Id = 49, TeamId = 49, Name = "Teddy", Slug = "teddy", IsChampion = false },
                new Mascot { Id = 50, TeamId = 50, Name = "Big Mo.", Slug = "big-mo", IsChampion = false },
                new Mascot { Id = 51, TeamId = 51, Name = "Kazoo", Slug = "kazoo", IsChampion = true },
                new Mascot { Id = 52, TeamId = 52, Name = "Slugger", Slug = "slugger", IsChampion = false },
                new Mascot { Id = 53, TeamId = 53, Name = "Shelly the Horse", Slug = "shelly-the-horse", IsChampion = false },
                new Mascot { Id = 54, TeamId = 54, Name = "Rusty Hook", Slug = "rusty-hook", IsChampion = false },
                new Mascot { Id = 55, TeamId = 55, Name = "Deuce", Slug = "deuce", IsChampion = false },
                new Mascot { Id = 56, TeamId = 56, Name = "Rocky RockHound", Slug = "rocky-rockhound", IsChampion = false },
                new Mascot { Id = 57, TeamId = 57, Name = "Sinker the Lake Creature", Slug = "sinker-the-lake-creature", IsChampion = false },
                new Mascot { Id = 58, TeamId = 58, Name = "Ballapeno", Slug = "ballapeno", IsChampion = true, TwitterHandle = "Ballapeno" },
                new Mascot { Id = 59, TeamId = 59, Name = "Louie", Slug = "louie-2", IsChampion = false },
                new Mascot { Id = 60, TeamId = 60, Name = "Hornsby", Slug = "hornsby", IsChampion = false, TwitterHandle = "Therealhornsby" },
                new Mascot { Id = 61, TeamId = 61, Name = "Torch", Slug = "torch", IsChampion = false },
                new Mascot { Id = 62, TeamId = 62, Name = "Wooly Bully", Slug = "wooly-bully", IsChampion = false, TwitterHandle = "woolybullymavs" },
                new Mascot { Id = 63, TeamId = 63, Name = "Bernie", Slug = "bernie", IsChampion = false },
                new Mascot { Id = 64, TeamId = 64, Name = "Thunder", Slug = "thunder", IsChampion = false, TwitterHandle = "ThundertheDog" },
                new Mascot { Id = 65, TeamId = 65, Name = "KaBoom!", Slug = "kaboom", IsChampion = false },
                new Mascot { Id = 66, TeamId = 66, Name = "Wally the Walnut", Slug = "wally-the-walnut", IsChampion = false },
                new Mascot { Id = 67, TeamId = 67, Name = "Tremor", Slug = "tremor", IsChampion = false },
                new Mascot { Id = 68, TeamId = 68, Name = "Gigante", Slug = "gigante", IsChampion = true },
                new Mascot { Id = 69, TeamId = 69, Name = "Splash", Slug = "splash", IsChampion = false },
                new Mascot { Id = 70, TeamId = 70, Name = "Tipper T. Bull", Slug = "tipper-t-bull", IsChampion = false },
                new Mascot { Id = 71, TeamId = 71, Name = "Muddy the Mudcat", Slug = "muddy-the-mudcat", IsChampion = false, TwitterHandle = "muddythemudcat" },
                new Mascot { Id = 72, TeamId = 72, Name = "Keyote", Slug = "keyote", IsChampion = false },
                new Mascot { Id = 73, TeamId = 73, Name = "Southpaw", Slug = "southpaw-2", IsChampion = false },
                new Mascot { Id = 74, TeamId = 74, Name = "Splash Pelican", Slug = "splash-pelican", IsChampion = true, TwitterHandle = "SplashPelican" },
                new Mascot { Id = 75, TeamId = 75, Name = "Uncle Slam", Slug = "uncle-slam", IsChampion = false },
                new Mascot { Id = 76, TeamId = 76, Name = "Mugsy", Slug = "mugsy", IsChampion = false, TwitterHandle = "SalemSoxMugsy" },
                new Mascot { Id = 77, TeamId = 77, Name = "Rocky Bluewinkle", Slug = "rocky-bluewinkle", IsChampion = false },
                new Mascot { Id = 78, TeamId = 78, Name = "Bolt", Slug = "bolt", IsChampion = false },
                new Mascot { Id = 79, TeamId = 79, Name = "Marty the Marauder", Slug = "marty-the-marauder", IsChampion = false },
                new Mascot { Id = 80, TeamId = 80, Name = "Manny the Manatee", Slug = "manny-the-manatee", IsChampion = false, TwitterHandle = "manny_manatee" },
                new Mascot { Id = 81, TeamId = 81, Name = "Stoney", Slug = "stoney", IsChampion = false },
                new Mascot { Id = 82, TeamId = 82, Name = "Phinley", Slug = "phinley", IsChampion = true, TwitterHandle = "PhinleyThresher" },
                new Mascot { Id = 83, TeamId = 83, Name = "Cubby", Slug = "cubby", IsChampion = false, TwitterHandle = "DCubsCubbysCrew" },
                new Mascot { Id = 84, TeamId = 84, Name = "D-Jay", Slug = "d-jay", IsChampion = false, TwitterHandle = "djaybluejay" },
                new Mascot { Id = 85, TeamId = 85, Name = "Miss-A-Miracle", Slug = "miss-a-miracle", IsChampion = false },
                new Mascot { Id = 86, TeamId = 86, Name = "Hamilton R. Head", Slug = "hamilton-r-head", IsChampion = false },
                new Mascot { Id = 87, TeamId = 87, Name = "Ace", Slug = "ace", IsChampion = false },
                new Mascot { Id = 88, TeamId = 88, Name = "Robbie the Redbird", Slug = "robbie-the-redbird", IsChampion = false },
                new Mascot { Id = 89, TeamId = 89, Name = "Klutch", Slug = "klutch", IsChampion = false, TwitterHandle = "Klutch_STLMets" },
                new Mascot { Id = 90, TeamId = 90, Name = "Blue", Slug = "blue", IsChampion = false, TwitterHandle = "Blue_TYMascot" },
                new Mascot { Id = 91, TeamId = 91, Name = "Snappy D. Turtle", Slug = "snappy-d-turtle", IsChampion = false },
                new Mascot { Id = 92, TeamId = 92, Name = "Roscoe the Grease Monkey", Slug = "roscoe-the-grease-monkey", IsChampion = false },
                new Mascot { Id = 93, TeamId = 93, Name = "Buzz", Slug = "buzz", IsChampion = false },
                new Mascot { Id = 94, TeamId = 94, Name = "Mr. Shucks", Slug = "mr-shucks", IsChampion = false },
                new Mascot { Id = 95, TeamId = 95, Name = "Louie The LumberKing", Slug = "louie-the-lumberking", IsChampion = false },
                new Mascot { Id = 96, TeamId = 96, Name = "Heater", Slug = "heater", IsChampion = false },
                new Mascot { Id = 97, TeamId = 97, Name = "Johnny TinCap", Slug = "johnny-tincap", IsChampion = false },
                new Mascot { Id = 98, TeamId = 98, Name = "Lou E. Loon", Slug = "lou-e-loon", IsChampion = false, TwitterHandle = "LouELoon" },
                new Mascot { Id = 99, TeamId = 99, Name = "Ozzie T. Cougar", Slug = "ozzie-t-cougar", IsChampion = false },
                new Mascot { Id = 100, TeamId = 100, Name = "Skipper", Slug = "skipper", IsChampion = false },
                new Mascot { Id = 101, TeamId = 101, Name = "Big Lug", Slug = "big-lug", IsChampion = false },
                new Mascot { Id = 102, TeamId = 102, Name = "Homer", Slug = "homer", IsChampion = true, TwitterHandle = "HomerPeoChiefs" },
                new Mascot { Id = 103, TeamId = 103, Name = "Rascal", Slug = "rascal-2", IsChampion = false },
                new Mascot { Id = 104, TeamId = 104, Name = "Swoop", Slug = "swoop", IsChampion = false, TwitterHandle = "SilverSwoop" },
                new Mascot { Id = 105, TeamId = 105, Name = "Crash the River Rascal", Slug = "crash-the-river-rascal", IsChampion = false },
                new Mascot { Id = 106, TeamId = 106, Name = "Fang T. Rattler", Slug = "fang-t-rattler", IsChampion = false, TwitterHandle = "Fang_T_Rattler" },
                new Mascot { Id = 107, TeamId = 107, Name = "Mr. Moon", Slug = "mr-moon", IsChampion = false },
                new Mascot { Id = 108, TeamId = 108, Name = "Auggie", Slug = "auggie", IsChampion = false },
                new Mascot { Id = 109, TeamId = 109, Name = "Charlie T. RiverDog", Slug = "charlie-t-riverdog", IsChampion = false, TwitterHandle = "CharlieRiverDog" },
                new Mascot { Id = 110, TeamId = 110, Name = "Sherman the Shorebird", Slug = "sherman-the-shorebird", IsChampion = false },
                new Mascot { Id = 111, TeamId = 111, Name = "Guilford the Grasshopper", Slug = "guilford-the-grasshopper", IsChampion = false },
                new Mascot { Id = 112, TeamId = 112, Name = "Reedy Rip'It", Slug = "reedy-ripit", IsChampion = false, TwitterHandle = "ReedyRipIt" },
                new Mascot { Id = 113, TeamId = 113, Name = "Woolie", Slug = "woolie", IsChampion = false },
                new Mascot { Id = 114, TeamId = 114, Name = "Conrad the Crawdad", Slug = "conrad-the-crawdad", IsChampion = false },
                new Mascot { Id = 115, TeamId = 115, Name = "Tim E. Gator", Slug = "tim-e-gator", IsChampion = false },
                new Mascot { Id = 116, TeamId = 116, Name = "Buster", Slug = "buster", IsChampion = false, TwitterHandle = "BlueClawsBuster" },
                new Mascot { Id = 117, TeamId = 117, Name = "Big L", Slug = "big-l", IsChampion = false },
                new Mascot { Id = 118, TeamId = 118, Name = "Romey", Slug = "romey", IsChampion = false },
                new Mascot { Id = 119, TeamId = 119, Name = "Gnate the Gnat", Slug = "gnate-the-gnat", IsChampion = true, TwitterHandle = "gnatethegnat" },
                new Mascot { Id = 120, TeamId = 120, Name = "Chuck", Slug = "chuck", IsChampion = false, TwitterHandle = "wv_powerCHUCK" },
                new Mascot { Id = 121, TeamId = 121, Name = "Ferrous", Slug = "ferrous", IsChampion = true },
                new Mascot { Id = 122, TeamId = 122, Name = "Abner", Slug = "abner", IsChampion = false },
                new Mascot { Id = 123, TeamId = 123, Name = "Homer", Slug = "homer-2", IsChampion = false },
                new Mascot { Id = 124, TeamId = 124, Name = "Sandy the Seagull", Slug = "sandy-the-seagull", IsChampion = false, TwitterHandle = "SandytheSeagull" },
                new Mascot { Id = 125, TeamId = 125, Name = "C.T. the Tiger", Slug = "ct-the-tiger", IsChampion = false },
                new Mascot { Id = 126, TeamId = 126, Name = "Rascal", Slug = "rascal-3", IsChampion = false, TwitterHandle = "HVRascal" },
                new Mascot { Id = 127, TeamId = 127, Name = "Bubba Grape", Slug = "bubba-grape", IsChampion = false },
                new Mascot { Id = 128, TeamId = 128, Name = "Canaligator", Slug = "canaligator", IsChampion = false, TwitterHandle = "Canaligator" },
                new Mascot { Id = 129, TeamId = 129, Name = "Scrappy", Slug = "scrappy", IsChampion = false },
                new Mascot { Id = 130, TeamId = 130, Name = "Ike the Spike", Slug = "ike-the-spike", IsChampion = false },
                new Mascot { Id = 131, TeamId = 131, Name = "Scooter the Holy Cow", Slug = "scooter-the-holy-cow", IsChampion = false },
                new Mascot { Id = 132, TeamId = 132, Name = "South Paw", Slug = "south-paw", IsChampion = false },
                new Mascot { Id = 133, TeamId = 133, Name = "Champ", Slug = "champ", IsChampion = false, TwitterHandle = "ChampVLM" },
                new Mascot { Id = 134, TeamId = 134, Name = "Boomer", Slug = "boomer-2", IsChampion = false, TwitterHandle = "thegreatboomer" },
                new Mascot { Id = 135, TeamId = 135, Name = "Humphrey Hawk", Slug = "humphrey-hawk", IsChampion = false, TwitterHandle = "HumphreyTheHawk" },
                new Mascot { Id = 136, TeamId = 136, Name = "Sluggo", Slug = "sluggo", IsChampion = false, TwitterHandle = "SluggoEmeralds" },
                new Mascot { Id = 137, TeamId = 137, Name = "Webbly", Slug = "webbly", IsChampion = false },
                new Mascot { Id = 138, TeamId = 138, Name = "Barley", Slug = "barley", IsChampion = true, TwitterHandle = "BarleytheHop" },
                new Mascot { Id = 139, TeamId = 139, Name = "Crater", Slug = "crater", IsChampion = false },
                new Mascot { Id = 140, TeamId = 140, Name = "Otto The Spokanasaurus", Slug = "otto-the-spokanasaurus", IsChampion = false },
                new Mascot { Id = 141, TeamId = 141, Name = "Dusty", Slug = "dusty", IsChampion = false },
                new Mascot { Id = 142, TeamId = 142, Name = "Bob Brown Bear", Slug = "bob-brown-bear", IsChampion = false, TwitterHandle = "bobbrownbear" },
                new Mascot { Id = 143, TeamId = 143, Name = "Baby Jay", Slug = "baby-jay", IsChampion = false },
                new Mascot { Id = 144, TeamId = 144, Name = "Dingbat", Slug = "dingbat", IsChampion = false, TwitterHandle = "DingbatBristol" },
                new Mascot { Id = 145, TeamId = 145, Name = "Bingo", Slug = "bingo", IsChampion = false },
                new Mascot { Id = 146, TeamId = 146, Name = "Blooper", Slug = "blooper", IsChampion = false },
                new Mascot { Id = 147, TeamId = 147, Name = "Rookie", Slug = "rookie", IsChampion = false },
                new Mascot { Id = 148, TeamId = 148, Name = "Tennessee Tess", Slug = "tennessee-tess", IsChampion = false },
                new Mascot { Id = 149, TeamId = 149, Name = "Jay Cee", Slug = "jay-cee", IsChampion = false },
                new Mascot { Id = 150, TeamId = 150, Name = "Slider", Slug = "slider", IsChampion = false },
                new Mascot { Id = 151, TeamId = 151, Name = "Roscoe The P-Ray Rooster", Slug = "roscoe-the-p-ray-rooster", IsChampion = true },
                new Mascot { Id = 152, TeamId = 152, Name = "Slyder", Slug = "slyder", IsChampion = false },
                new Mascot { Id = 153, TeamId = 153, Name = "Homer", Slug = "homer-3", IsChampion = false, TwitterHandle = "HomerMustang" },
                new Mascot { Id = 154, TeamId = 154, Name = "Corky", Slug = "corky", IsChampion = false, TwitterHandle = "corkythecoyote" },
                new Mascot { Id = 155, TeamId = 155, Name = "Orbit", Slug = "orbit-3", IsChampion = true },
                new Mascot { Id = 156, TeamId = 156, Name = "Clark the Cougar", Slug = "clark-the-cougar", IsChampion = false },
                new Mascot { Id = 157, TeamId = 157, Name = "Charlie the Chukar", Slug = "charlie-the-chukar", IsChampion = false },
                new Mascot { Id = 158, TeamId = 158, Name = "Ollie Osprey", Slug = "ollie-osprey", IsChampion = false },
                new Mascot { Id = 159, TeamId = 159, Name = "Oggie", Slug = "oggie", IsChampion = false },
                new Mascot { Id = 160, TeamId = 160, Name = "Hootz", Slug = "hootz", IsChampion = false },
            });

            context.SaveChanges();

            context.Teams.AddRange(new[]
            {
                new Team { Id = 1, LeagueId = 6, Name = "Buffalo Bisons", Slug = "buffalo-bisons" },
                new Team { Id = 2, LeagueId = 6, Name = "Charlotte Knights", Slug = "charlotte-knights" },
                new Team { Id = 3, LeagueId = 6, Name = "Columbus Clippers", Slug = "columbus-clippers" },
                new Team { Id = 4, LeagueId = 6, Name = "Durham Bulls", Slug = "durham-bulls" },
                new Team { Id = 5, LeagueId = 6, Name = "Gwinnett Braves", Slug = "gwinnett-braves" },
                new Team { Id = 6, LeagueId = 6, Name = "Indianapolis Indians", Slug = "indianapolis-indians" },
                new Team { Id = 7, LeagueId = 6, Name = "Lehigh Valley IronPigs", Slug = "lehigh-valley-ironpigs" },
                new Team { Id = 8, LeagueId = 6, Name = "Louisville Bats", Slug = "louisville-bats" },
                new Team { Id = 9, LeagueId = 6, Name = "Norfolk Tides", Slug = "norfolk-tides" },
                new Team { Id = 10, LeagueId = 6, Name = "Pawtucket Red Sox", Slug = "pawtucket-red-sox" },
                new Team { Id = 11, LeagueId = 6, Name = "Rochester Red Wings", Slug = "rochester-red-wings" },
                new Team { Id = 12, LeagueId = 6, Name = "Scranton/WB RailRiders", Slug = "scrantonwb-railriders" },
                new Team { Id = 13, LeagueId = 6, Name = "Syracuse Chiefs", Slug = "syracuse-chiefs" },
                new Team { Id = 14, LeagueId = 6, Name = "Toledo Mud Hens", Slug = "toledo-mud-hens" },
                new Team { Id = 15, LeagueId = 10, Name = "Albuquerque Isotopes", Slug = "albuquerque-isotopes" },
                new Team { Id = 16, LeagueId = 10, Name = "Colorado Springs Sky Sox", Slug = "colorado-springs-sky-sox" },
                new Team { Id = 17, LeagueId = 10, Name = "Fresno Grizzlies", Slug = "fresno-grizzlies" },
                new Team { Id = 18, LeagueId = 10, Name = "Iowa Cubs", Slug = "iowa-cubs" },
                new Team { Id = 19, LeagueId = 10, Name = "Las Vegas 51s", Slug = "las-vegas-51s" },
                new Team { Id = 20, LeagueId = 10, Name = "Memphis Redbirds", Slug = "memphis-redbirds" },
                new Team { Id = 21, LeagueId = 10, Name = "Nashville Sounds", Slug = "nashville-sounds" },
                new Team { Id = 22, LeagueId = 10, Name = "New Orleans Zephyrs", Slug = "new-orleans-zephyrs" },
                new Team { Id = 23, LeagueId = 10, Name = "Oklahoma City RedHawks", Slug = "oklahoma-city-redhawks" },
                new Team { Id = 24, LeagueId = 10, Name = "Omaha Storm Chasers", Slug = "omaha-storm-chasers" },
                new Team { Id = 25, LeagueId = 10, Name = "Reno Aces", Slug = "reno-aces" },
                new Team { Id = 26, LeagueId = 10, Name = "Round Rock Express", Slug = "round-rock-express" },
                new Team { Id = 27, LeagueId = 10, Name = "Sacramento River Cats", Slug = "sacramento-river-cats" },
                new Team { Id = 28, LeagueId = 10, Name = "Salt Lake Bees", Slug = "salt-lake-bees" },
                new Team { Id = 29, LeagueId = 10, Name = "Tacoma Rainiers", Slug = "tacoma-rainiers" },
                new Team { Id = 30, LeagueId = 10, Name = "Tucson Padres", Slug = "tucson-padres" },
                new Team { Id = 31, LeagueId = 4, Name = "Akron Aeros", Slug = "akron-aeros" },
                new Team { Id = 32, LeagueId = 4, Name = "Altoona Curve", Slug = "altoona-curve" },
                new Team { Id = 33, LeagueId = 4, Name = "Binghamton Mets", Slug = "binghamton-mets" },
                new Team { Id = 34, LeagueId = 4, Name = "Bowie Baysox", Slug = "bowie-baysox" },
                new Team { Id = 35, LeagueId = 4, Name = "Erie SeaWolves", Slug = "erie-seawolves" },
                new Team { Id = 36, LeagueId = 4, Name = "Harrisburg Senators", Slug = "harrisburg-senators" },
                new Team { Id = 37, LeagueId = 4, Name = "New Britain Rock Cats", Slug = "new-britain-rock-cats" },
                new Team { Id = 38, LeagueId = 4, Name = "New Hampshire Fisher Cats", Slug = "new-hampshire-fisher-cats" },
                new Team { Id = 39, LeagueId = 4, Name = "Portland Sea Dogs", Slug = "portland-sea-dogs" },
                new Team { Id = 40, LeagueId = 4, Name = "Reading Fightin Phils", Slug = "reading-fightin-phils" },
                new Team { Id = 41, LeagueId = 4, Name = "Richmond Flying Squirrels", Slug = "richmond-flying-squirrels" },
                new Team { Id = 42, LeagueId = 4, Name = "Trenton Thunder", Slug = "trenton-thunder" },
                new Team { Id = 43, LeagueId = 13, Name = "Birmingham Barons", Slug = "birmingham-barons" },
                new Team { Id = 44, LeagueId = 13, Name = "Chattanooga Lookouts", Slug = "chattanooga-lookouts" },
                new Team { Id = 45, LeagueId = 13, Name = "Huntsville Stars", Slug = "huntsville-stars" },
                new Team { Id = 46, LeagueId = 13, Name = "Jackson Generals", Slug = "jackson-generals" },
                new Team { Id = 47, LeagueId = 13, Name = "Jacksonville Suns", Slug = "jacksonville-suns" },
                new Team { Id = 48, LeagueId = 13, Name = "Mississippi Braves", Slug = "mississippi-braves" },
                new Team { Id = 49, LeagueId = 13, Name = "Mobile BayBears", Slug = "mobile-baybears" },
                new Team { Id = 50, LeagueId = 13, Name = "Montgomery Biscuits", Slug = "montgomery-biscuits" },
                new Team { Id = 51, LeagueId = 13, Name = "Pensacola Blue Wahoos", Slug = "pensacola-blue-wahoos" },
                new Team { Id = 52, LeagueId = 13, Name = "Tennessee Smokies", Slug = "tennessee-smokies" },
                new Team { Id = 53, LeagueId = 14, Name = "Arkansas Travelers", Slug = "arkansas-travelers" },
                new Team { Id = 54, LeagueId = 14, Name = "Corpus Christi Hooks", Slug = "corpus-christi-hooks" },
                new Team { Id = 55, LeagueId = 14, Name = "Frisco RoughRiders", Slug = "frisco-roughriders" },
                new Team { Id = 56, LeagueId = 14, Name = "Midland RockHounds", Slug = "midland-rockhounds" },
                new Team { Id = 57, LeagueId = 14, Name = "NW Arkansas Naturals", Slug = "nw-arkansas-naturals" },
                new Team { Id = 58, LeagueId = 14, Name = "San Antonio Missions", Slug = "san-antonio-missions" },
                new Team { Id = 59, LeagueId = 14, Name = "Springfield Cardinals", Slug = "springfield-cardinals" },
                new Team { Id = 60, LeagueId = 14, Name = "Tulsa Drillers", Slug = "tulsa-drillers" },
                new Team { Id = 61, LeagueId = 2, Name = "Bakersfield Blaze", Slug = "bakersfield-blaze" },
                new Team { Id = 62, LeagueId = 2, Name = "High Desert Mavericks", Slug = "high-desert-mavericks" },
                new Team { Id = 63, LeagueId = 2, Name = "Inland Empire 66ers", Slug = "inland-empire-66ers" },
                new Team { Id = 64, LeagueId = 2, Name = "Lake Elsinore Storm", Slug = "lake-elsinore-storm" },
                new Team { Id = 65, LeagueId = 2, Name = "Lancaster JetHawks", Slug = "lancaster-jethawks" },
                new Team { Id = 66, LeagueId = 2, Name = "Modesto Nuts", Slug = "modesto-nuts" },
                new Team { Id = 67, LeagueId = 2, Name = "Rancho Cuca. Quakes", Slug = "rancho-cuca-quakes" },
                new Team { Id = 68, LeagueId = 2, Name = "San Jose Giants", Slug = "san-jose-giants" },
                new Team { Id = 69, LeagueId = 2, Name = "Stockton Ports", Slug = "stockton-ports" },
                new Team { Id = 70, LeagueId = 2, Name = "Visalia Rawhide", Slug = "visalia-rawhide" },
                new Team { Id = 71, LeagueId = 3, Name = "Carolina Mudcats", Slug = "carolina-mudcats" },
                new Team { Id = 72, LeagueId = 3, Name = "Frederick Keys", Slug = "frederick-keys" },
                new Team { Id = 73, LeagueId = 3, Name = "Lynchburg Hillcats", Slug = "lynchburg-hillcats" },
                new Team { Id = 74, LeagueId = 3, Name = "Myrtle Beach Pelicans", Slug = "myrtle-beach-pelicans" },
                new Team { Id = 75, LeagueId = 3, Name = "Potomac Nationals", Slug = "potomac-nationals" },
                new Team { Id = 76, LeagueId = 3, Name = "Salem Red Sox", Slug = "salem-red-sox" },
                new Team { Id = 77, LeagueId = 3, Name = "Wilmington Blue Rocks", Slug = "wilmington-blue-rocks" },
                new Team { Id = 78, LeagueId = 3, Name = "Winston-Salem Dash", Slug = "winston-salem-dash" },
                new Team { Id = 79, LeagueId = 5, Name = "Bradenton Marauders", Slug = "bradenton-marauders" },
                new Team { Id = 80, LeagueId = 5, Name = "Brevard County Manatees", Slug = "brevard-county-manatees" },
                new Team { Id = 81, LeagueId = 5, Name = "Charlotte Stone Crabs", Slug = "charlotte-stone-crabs" },
                new Team { Id = 82, LeagueId = 5, Name = "Clearwater Threshers", Slug = "clearwater-threshers" },
                new Team { Id = 83, LeagueId = 5, Name = "Daytona Cubs", Slug = "daytona-cubs" },
                new Team { Id = 84, LeagueId = 5, Name = "Dunedin Blue Jays", Slug = "dunedin-blue-jays" },
                new Team { Id = 85, LeagueId = 5, Name = "Fort Myers Miracle", Slug = "fort-myers-miracle" },
                new Team { Id = 86, LeagueId = 5, Name = "Jupiter Hammerheads", Slug = "jupiter-hammerheads" },
                new Team { Id = 87, LeagueId = 5, Name = "Lakeland Flying Tigers", Slug = "lakeland-flying-tigers" },
                new Team { Id = 88, LeagueId = 5, Name = "Palm Beach Cardinals", Slug = "palm-beach-cardinals" },
                new Team { Id = 89, LeagueId = 5, Name = "St. Lucie Mets", Slug = "st-lucie-mets" },
                new Team { Id = 90, LeagueId = 5, Name = "Tampa Yankees", Slug = "tampa-yankees" },
                new Team { Id = 91, LeagueId = 7, Name = "Beloit Snappers", Slug = "beloit-snappers" },
                new Team { Id = 92, LeagueId = 7, Name = "Bowling Green Hot Rods", Slug = "bowling-green-hot-rods" },
                new Team { Id = 93, LeagueId = 7, Name = "Burlington Bees", Slug = "burlington-bees" },
                new Team { Id = 94, LeagueId = 7, Name = "Cedar Rapids Kernels", Slug = "cedar-rapids-kernels" },
                new Team { Id = 95, LeagueId = 7, Name = "Clinton LumberKings", Slug = "clinton-lumberkings" },
                new Team { Id = 96, LeagueId = 7, Name = "Dayton Dragons", Slug = "dayton-dragons" },
                new Team { Id = 97, LeagueId = 7, Name = "Fort Wayne TinCaps", Slug = "fort-wayne-tincaps" },
                new Team { Id = 98, LeagueId = 7, Name = "Great Lakes Loons", Slug = "great-lakes-loons" },
                new Team { Id = 99, LeagueId = 7, Name = "Kane County Cougars", Slug = "kane-county-cougars" },
                new Team { Id = 100, LeagueId = 7, Name = "Lake County Captains", Slug = "lake-county-captains" },
                new Team { Id = 101, LeagueId = 7, Name = "Lansing Lugnuts", Slug = "lansing-lugnuts" },
                new Team { Id = 102, LeagueId = 7, Name = "Peoria Chiefs", Slug = "peoria-chiefs" },
                new Team { Id = 103, LeagueId = 7, Name = "Quad Cities River Bandits", Slug = "quad-cities-river-bandits" },
                new Team { Id = 104, LeagueId = 7, Name = "South Bend Silver Hawks", Slug = "south-bend-silver-hawks" },
                new Team { Id = 105, LeagueId = 7, Name = "West Michigan Whitecaps", Slug = "west-michigan-whitecaps" },
                new Team { Id = 106, LeagueId = 7, Name = "Wisconsin Timber Rattlers", Slug = "wisconsin-timber-rattlers" },
                new Team { Id = 107, LeagueId = 12, Name = "Asheville Tourists", Slug = "asheville-tourists" },
                new Team { Id = 108, LeagueId = 12, Name = "Augusta GreenJackets", Slug = "augusta-greenjackets" },
                new Team { Id = 109, LeagueId = 12, Name = "Charleston RiverDogs", Slug = "charleston-riverdogs" },
                new Team { Id = 110, LeagueId = 12, Name = "Delmarva Shorebirds", Slug = "delmarva-shorebirds" },
                new Team { Id = 111, LeagueId = 12, Name = "Greensboro Grasshoppers", Slug = "greensboro-grasshoppers" },
                new Team { Id = 112, LeagueId = 12, Name = "Greenville Drive", Slug = "greenville-drive" },
                new Team { Id = 113, LeagueId = 12, Name = "Hagerstown Suns", Slug = "hagerstown-suns" },
                new Team { Id = 114, LeagueId = 12, Name = "Hickory Crawdads", Slug = "hickory-crawdads" },
                new Team { Id = 115, LeagueId = 12, Name = "Kannapolis Intimidators", Slug = "kannapolis-intimidators" },
                new Team { Id = 116, LeagueId = 12, Name = "Lakewood BlueClaws", Slug = "lakewood-blueclaws" },
                new Team { Id = 117, LeagueId = 12, Name = "Lexington Legends", Slug = "lexington-legends" },
                new Team { Id = 118, LeagueId = 12, Name = "Rome Braves", Slug = "rome-braves" },
                new Team { Id = 119, LeagueId = 12, Name = "Savannah Sand Gnats", Slug = "savannah-sand-gnats" },
                new Team { Id = 120, LeagueId = 12, Name = "West Virginia Power", Slug = "west-virginia-power" },
                new Team { Id = 121, LeagueId = 8, Name = "Aberdeen IronBirds", Slug = "aberdeen-ironbirds" },
                new Team { Id = 122, LeagueId = 8, Name = "Auburn Doubledays", Slug = "auburn-doubledays" },
                new Team { Id = 123, LeagueId = 8, Name = "Batavia Muckdogs", Slug = "batavia-muckdogs" },
                new Team { Id = 124, LeagueId = 8, Name = "Brooklyn Cyclones", Slug = "brooklyn-cyclones" },
                new Team { Id = 125, LeagueId = 8, Name = "Connecticut Tigers", Slug = "connecticut-tigers" },
                new Team { Id = 126, LeagueId = 8, Name = "Hudson Valley Renegades", Slug = "hudson-valley-renegades" },
                new Team { Id = 127, LeagueId = 8, Name = "Jamestown Jammers", Slug = "jamestown-jammers" },
                new Team { Id = 128, LeagueId = 8, Name = "Lowell Spinners", Slug = "lowell-spinners" },
                new Team { Id = 129, LeagueId = 8, Name = "Mahoning Valley Scrappers", Slug = "mahoning-valley-scrappers" },
                new Team { Id = 130, LeagueId = 8, Name = "State College Spikes", Slug = "state-college-spikes" },
                new Team { Id = 131, LeagueId = 8, Name = "Staten Island Yankees", Slug = "staten-island-yankees" },
                new Team { Id = 132, LeagueId = 8, Name = "Tri-City ValleyCats", Slug = "tri-city-valleycats" },
                new Team { Id = 133, LeagueId = 8, Name = "Vermont Lake Monsters", Slug = "vermont-lake-monsters" },
                new Team { Id = 134, LeagueId = 8, Name = "Williamsport Crosscutters", Slug = "williamsport-crosscutters" },
                new Team { Id = 135, LeagueId = 9, Name = "Boise Hawks", Slug = "boise-hawks" },
                new Team { Id = 136, LeagueId = 9, Name = "Eugene Emeralds", Slug = "eugene-emeralds" },
                new Team { Id = 137, LeagueId = 9, Name = "Everett AquaSox", Slug = "everett-aquasox" },
                new Team { Id = 138, LeagueId = 9, Name = "Hillsboro Hops", Slug = "hillsboro-hops" },
                new Team { Id = 139, LeagueId = 9, Name = "Salem-Keizer Volcanoes", Slug = "salem-keizer-volcanoes" },
                new Team { Id = 140, LeagueId = 9, Name = "Spokane Indians", Slug = "spokane-indians" },
                new Team { Id = 141, LeagueId = 9, Name = "Tri-City Dust Devils", Slug = "tri-city-dust-devils" },
                new Team { Id = 142, LeagueId = 9, Name = "Vancouver Canadians", Slug = "vancouver-canadians" },
                new Team { Id = 143, LeagueId = 1, Name = "Bluefield Blue Jays", Slug = "bluefield-blue-jays" },
                new Team { Id = 144, LeagueId = 1, Name = "Bristol White Sox", Slug = "bristol-white-sox" },
                new Team { Id = 145, LeagueId = 1, Name = "Burlington Royals", Slug = "burlington-royals" },
                new Team { Id = 146, LeagueId = 1, Name = "Danville Braves", Slug = "danville-braves" },
                new Team { Id = 147, LeagueId = 1, Name = "Elizabethton Twins", Slug = "elizabethton-twins" },
                new Team { Id = 148, LeagueId = 1, Name = "Greeneville Astros", Slug = "greeneville-astros" },
                new Team { Id = 149, LeagueId = 1, Name = "Johnson City Cardinals", Slug = "johnson-city-cardinals" },
                new Team { Id = 150, LeagueId = 1, Name = "Kingsport Mets", Slug = "kingsport-mets" },
                new Team { Id = 151, LeagueId = 1, Name = "Princeton Rays", Slug = "princeton-rays" },
                new Team { Id = 152, LeagueId = 1, Name = "Pulaski Mariners", Slug = "pulaski-mariners" },
                new Team { Id = 153, LeagueId = 11, Name = "Billings Mustangs", Slug = "billings-mustangs" },
                new Team { Id = 154, LeagueId = 11, Name = "Grand Junction Rockies", Slug = "grand-junction-rockies" },
                new Team { Id = 155, LeagueId = 11, Name = "Great Falls Voyagers", Slug = "great-falls-voyagers" },
                new Team { Id = 156, LeagueId = 11, Name = "Helena Brewers", Slug = "helena-brewers" },
                new Team { Id = 157, LeagueId = 11, Name = "Idaho Falls Chukars", Slug = "idaho-falls-chukars" },
                new Team { Id = 158, LeagueId = 11, Name = "Missoula Osprey", Slug = "missoula-osprey" },
                new Team { Id = 159, LeagueId = 11, Name = "Ogden Raptors", Slug = "ogden-raptors" },
                new Team { Id = 160, LeagueId = 11, Name = "Orem Owlz", Slug = "orem-owlz" }
            });

            context.SaveChanges();
        }
    }
}